### ISSUE TITLE
Error: Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by aitesam961** [nmanumr/quizsliver#10]
![image](https://user-images.githubusercontent.com/67455292/163713275-3492b656-ba96-40d2-8382-bd48c86a3388.png)

**Comment by Khizar1017** [comment]
Facing Same issue

**Comment by nmanumr** [comment]
Can you please confirm that the zip contains the mainfest.json file? Because, I was working for me. Anyways, I'm reuploading the zip zip there that is working for me:

[QuizSliver-v1.3.5.zip](https://github.com/nmanumr/quizsliver/files/8501808/QuizSliver-v1.3.5.zip)

**Comment by Khizar1017** [comment]
There wasn’t manifest file I tried to modify domains of last release but
didn’t worked I’ll try this one and get back to you

**Comment by aitesam961** [comment]
The problem is with the Unzip Distro tree.
Upon Unzipping, Two separate Files appear to be there. If we go a step ahead inside the Unzipped folder and select dist 2 at"load Unpacked", It works fine
![image](https://user-images.githubusercontent.com/67455292/163719440-19527eb4-91eb-4c97-9d4a-0f85b283487f.png)

**Comment by aitesam961** [comment]
Thanks @nmanumr for your prompt feedback and contribution in maintaining this repo

**Comment by Khizar1017** [comment]
the issue being resolved, Keep up the good work fellow
