### ISSUE TITLE
 Manifest file is missing or unreadable Could not load manifest

### ISSUE THREAD

**Issue by mat2002** [nmanumr/quizsliver#17]
I just downloaded as zip this repository. When I try to load it, it gives this error.
![1](https://user-images.githubusercontent.com/95518949/194920980-e7401d4f-6630-40ac-b594-5e0f333bab9c.jpg)

**Comment by nmanumr** [comment]
This is related to #11. The only work arround yet is to try downloading some older version Im sure one of them is built properly.

**Comment by mat2002** [comment]
Ok brother thanks

**Comment by nmanumr** [comment]
try v1.3.7

**Comment by samiraj23** [comment]
> try v1.3.7

same problem on  v1.3.7 again and again

**Comment by samiraj23** [comment]
03430064610 WhatsApp  nomijaj647@gmail.ccom contact me

**Comment by ossamamehmood** [comment]
> 03430064610 WhatsApp  nomijaj647@gmail.ccom contact me

Can you here what's the problem please share screenshot?

**Comment by samiraj23** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/115919487/196135457-76d44704-fa00-454f-900a-1c1e79f820f1.png)

**Comment by ossamamehmood** [comment]
You selected the wrong folder

> Choose Right Path
> Make Sure Load Unpacked > Select the dist folder inside the quizsliver-1.3.7

It'll work good luck

**Comment by 20wh1a1230** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/115919487/196135457-76d44704-fa00-454f-900a-1c1e79f820f1.png)

im facing the same issue cud uh plz tell me
