### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'innerText')

### ISSUE THREAD

**Issue by syedawaisshah** [nmanumr/quizsliver#28]
![quiz silver](https://user-images.githubusercontent.com/119275504/234204581-4600c33a-e1f1-4972-8ce1-829915581750.PNG)

when i  update the manifest file by giving the Comsats university Abbottabad link it give me this error plz help me to resolve this issue.

**Comment by nmanumr** [comment]
You can safely ignore this error
