### ISSUE TITLE
Incorrect Responses for Islamic Studies

### ISSUE THREAD

**Issue by aitesam961** [nmanumr/quizsliver#29]
Hi everyone,
During the SP23 session, it came to light that the extension marks Incorrect answers which I personally experienced along with several of my batch mates
Issue appeared for: 
- cuonline.cuiwah.edu.pk:8095
- HUM-110
- Firefox, Ubuntu 22.04 LTS (some windows/Edge Machines experienced as well)

The second part of issue is that the HUM110 course doesn't open Up if extension is enabled. You have to disable, naviagate to **TAKE QUIZ** page and then Enable works.
I got 6/15 correct options.

**My best Guess is that the MCQs option numbers are interchanged**

**Comment by aitesam961** [comment]
For those struggling with similar situation, ChatGPT Exists. Just throw the whole question with options at it... :D

**Comment by nmanumr** [comment]
I fixed both if these issues a while ago so either you are actually using the older version of the extension or theses issues are raised again
