### ISSUE TITLE
Uncaught type error

### ISSUE THREAD

**Issue by Techsupporthehehe** [nmanumr/quizsliver#7]
![WhatsApp Image 2021-10-08 at 10 38 29 PM](https://user-images.githubusercontent.com/92199802/136645889-5ab630b2-621e-4138-94aa-69d451d140a1.jpeg)

This seems to pop up whenever a open the student portal.

**Comment by nmanumr** [comment]
Thanks for reporting the issue will look into it.

**Comment by Ranafarhan3568** [comment]
![image](https://user-images.githubusercontent.com/98528503/161126331-0596775c-75a9-4fb6-816d-f7a79de95ace.png)

**Comment by nmanumr** [comment]
try v1.3.7
